<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findOneById($id)
    {
        return $this->createQueryBuilder('p')
            ->select('p, c')
            ->join('p.category', 'c')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findAllWithDependencies()
    {
        return $this->createQueryBuilder('p')
            ->select('p, c')
            ->join('p.category', 'c')
            ->getQuery()
            ->getResult();
    }
}
