security:

    encoders:
            AppBundle\Entity\User:
                algorithm: bcrypt
                cost: 12
    providers:
        main:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
